"""
Sends formatted trade-setup alerts to Telegram. Requires TELEGRAM_BOT_TOKEN
and TELEGRAM_CHAT_ID to be set in config.py (see the instructions there).
"""
import requests
import config


def send_telegram_message(text: str) -> bool:
    if "PASTE_YOUR" in config.TELEGRAM_BOT_TOKEN:
        print("[telegram_alert] Bot token not configured -- skipping send. "
              "Message would have been:\n" + text)
        return False
    url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendMessage"
    try:
        resp = requests.post(url, data={
            "chat_id": config.TELEGRAM_CHAT_ID,
            "text": text,
            "parse_mode": "Markdown",
        }, timeout=10)
        return resp.status_code == 200
    except Exception as e:
        print(f"[telegram_alert] Failed to send: {e}")
        return False


def format_pattern_alert(market: str, ticker: str, timeframe: str, pattern,
                          entry: float, stop: float, t1: float, t2: float, t3: float,
                          confluence: dict, status: str) -> str:
    """
    status: 'CONFIRMED' (D printed, trade the PRZ now) or 'WATCHING'
    (approaching PRZ, not confirmed yet -- heads up only).
    """
    direction_word = "LONG" if pattern.direction.value == "bullish" else "SHORT"
    risk_per_unit = abs(entry - stop)
    reward_t2 = abs(t2 - entry)
    rr = round(reward_t2 / risk_per_unit, 2) if risk_per_unit else None

    rsi_note = confluence["rsi"]["note"]
    vol_note = confluence["volume"]["note"]
    htf_note = confluence["htf_trend"]["note"]

    emoji = "\U0001F7E2" if status == "CONFIRMED" else "\U0001F440"

    lines = [
        f"{emoji} *{status}: {pattern.name} ({direction_word})*",
        f"*{ticker}* -- {market} -- {timeframe}",
        "",
        f"*Why this trade:* A {pattern.name} pattern has "
        f"{'completed' if status == 'CONFIRMED' else 'nearly completed'} at point D, "
        f"projecting a {'reversal higher' if direction_word == 'LONG' else 'reversal lower'} "
        f"from the {'X-A-B-C swing' if not pattern.ratios.get('CD/XC') else 'X-C swing'}.",
        f"Ratio quality score: {confluence['base_quality_score']}/100 "
        f"(confluence-adjusted: {confluence['adjusted_score']}/100).",
        f"RSI: {rsi_note}",
        f"Volume: {vol_note}",
        f"HTF trend: {htf_note}",
        "",
        f"*Entry:* {entry:.5f}  (PRZ)",
        f"*Stop Loss:* {stop:.5f}  (beyond point X + ATR buffer)",
        f"*Target 1 (0.382 of CD):* {t1:.5f} -- close 1/3, move stop to breakeven",
        f"*Target 2 (0.618 of CD):* {t2:.5f} -- close 1/3",
        f"*Target 3 (point A):* {t3:.5f} -- close remainder / trail",
        f"*Risk:Reward to T2:* ~{rr}R" if rr else "",
        "",
        f"Ratios: {pattern.ratios}",
    ]
    return "\n".join(l for l in lines if l is not None)


def _format_eta_line(eta: dict) -> str:
    if not eta or not eta.get("timing"):
        return ""
    t1 = eta["timing"].get("T1", {})
    t2 = eta["timing"].get("T2", {})
    if not t1 or t1.get("n_reached", 0) == 0:
        return "\n_No historical timing data yet for this instrument/pattern._"
    basis = "this exact pattern" if eta.get("specific") else "this instrument (blended across pattern types)"
    lines = [f"\n*Historical timing* (based on {eta['n_trades_used']} past trades on {basis}):"]
    if t1.get("n_reached"):
        lines.append(f"  T1 typically hit in ~{t1['median_bars']} bars (median), range {t1['min_bars']}-{t1['max_bars']}")
    if t2.get("n_reached"):
        lines.append(f"  T2 typically hit in ~{t2['median_bars']} bars (median), range {t2['min_bars']}-{t2['max_bars']}")
    lines.append("_This is a statistical tendency from past trades, not a guarantee._")
    return "\n".join(lines)


def format_action_alert(action: str, setup: dict, current_price: float, confluence: dict = None,
                         eta: dict = None) -> str:
    """
    Builds the explicit, unambiguous action message. This is the one that
    matters for actually trading -- the pattern-completion alert above is
    informational; these are the "do something now" messages, generated by
    trade_manager.py as a setup advances through its lifecycle.
    """
    ticker, market, tf = setup["ticker"], setup["market"], setup["timeframe"]
    pattern_name, direction = setup["pattern"], setup["direction"]
    direction_word = "LONG" if direction == "bullish" else "SHORT"

    if action == "ENTER_NOW":
        header = f"\U0001F7E2\U0001F7E2 *ENTER NOW -- {direction_word} {ticker}*"
        reason = (
            f"{pattern_name} pattern completed AND price has printed a confirmation candle "
            f"AND momentum (RSI or MACD) confirms the reversal. All three conditions are met -- "
            f"this is a full trade signal, not just a watch."
        )
        body = [
            header,
            f"*{ticker}* -- {market} -- {tf}   *{pattern_name}* ({direction_word})",
            "",
            f"*Reason:* {reason}",
            "",
            f"*ENTRY:* {setup['entry']:.5f}  (current price: {current_price:.5f})",
            f"*STOP LOSS:* {setup['stop']:.5f}",
            f"*TARGET 1 (0.382 CD):* {setup['t1']:.5f} -- close 1/3, then move stop to breakeven",
            f"*TARGET 2 (0.618 CD):* {setup['t2']:.5f} -- close 1/3",
            f"*TARGET 3 (point A):* {setup['t3']:.5f} -- close remainder",
        ]
        if confluence:
            body += ["", f"Candlestick: {confluence['candlestick']['note']}",
                      f"RSI: {confluence['rsi']['note']}", f"MACD: {confluence['macd']['note']}",
                      f"ADX: {confluence['adx']['note']}"]
        eta_line = _format_eta_line(eta)
        if eta_line:
            body.append(eta_line)
        return "\n".join(body)

    if action == "EXIT_PARTIAL_T1":
        return "\n".join([
            f"\U0001F7E1 *EXIT NOW -- Take Partial Profit (Target 1)*",
            f"*{ticker}* -- {market} -- {tf}   *{pattern_name}* ({direction_word})",
            "",
            f"Target 1 ({setup['t1']:.5f}) has been reached (current price: {current_price:.5f}).",
            f"*Action:* Close 1/3 of your position now. Move your stop loss to breakeven "
            f"({setup['entry']:.5f}) on the remainder -- this trade can no longer be a loser.",
            f"Remaining targets: T2 = {setup['t2']:.5f}, T3 = {setup['t3']:.5f}",
        ])

    if action == "EXIT_PARTIAL_T2":
        return "\n".join([
            f"\U0001F7E1 *EXIT NOW -- Take Partial Profit (Target 2)*",
            f"*{ticker}* -- {market} -- {tf}   *{pattern_name}* ({direction_word})",
            "",
            f"Target 2 ({setup['t2']:.5f}) has been reached (current price: {current_price:.5f}).",
            f"*Action:* Close another 1/3 of your position now. Stop remains at breakeven "
            f"({setup['stop']:.5f}) on the final third.",
            f"Final target: T3 = {setup['t3']:.5f} (point A) -- ride or trail the rest.",
        ])

    if action == "EXIT_FULL_T3":
        return "\n".join([
            f"\U0001F534 *EXIT NOW -- Close Full Position (Target 3 / Point A hit)*",
            f"*{ticker}* -- {market} -- {tf}   *{pattern_name}* ({direction_word})",
            "",
            f"Target 3 / point A ({setup['t3']:.5f}) has been reached (current price: {current_price:.5f}).",
            f"*Action:* Close your remaining position. Trade complete.",
        ])

    if action == "EXIT_STOP":
        frac = setup.get('fraction_remaining', 1.0)
        loss_note = ("Loss is capped near breakeven since T1 had already been banked."
                     if frac < 1.0 else "This is a full stop-out -- the pattern failed.")
        return "\n".join([
            f"\U0001F534 *EXIT NOW -- Stop Loss Hit*",
            f"*{ticker}* -- {market} -- {tf}   *{pattern_name}* ({direction_word})",
            "",
            f"Stop ({setup['stop']:.5f}) has been hit (current price: {current_price:.5f}).",
            f"*Action:* Close the remaining position immediately if your broker/platform hasn't "
            f"already stopped you out. {loss_note}",
        ])

    if action == "EXIT_TRAILING_STOP":
        return "\n".join([
            f"\U0001F534 *EXIT NOW -- Trailing Stop Hit*",
            f"*{ticker}* -- {market} -- {tf}   *{pattern_name}* ({direction_word})",
            "",
            f"After Target 2, the stop was trailing behind price instead of waiting for a fixed "
            f"Target 3 -- it just got hit at {setup['stop']:.5f} (current price: {current_price:.5f}).",
            f"*Action:* Close the remaining position. This let the trade run further than the "
            f"original Target 3 before locking in -- check the trade log to see how far it extended.",
        ])

    if action == "SETUP_INVALIDATED":
        return "\n".join([
            f"\u26AA *Setup invalidated -- no trade*",
            f"*{ticker}* -- {market} -- {tf}   *{pattern_name}* ({direction_word})",
            "",
            f"Price traded through point X before a confirmation candle appeared. "
            f"This pattern is no longer valid -- do not enter.",
        ])

    return ""
